config/routes.rb
Rails.application.routes.draw do
  resources :resposta
  resources :pergunta
  resources :pergunta
  devise_for :usuarios
  
  get '/menu' => 'pergunta#menu'
  get '/randomize/:nivel' => 'pergunta#randomize', as: 'randomize'
  get '/listar/:nivel/:reforco' => 'pergunta#listar'

  get '/nivel/:nivel/:ordem' => 'resposta#nivel', as: "nivel"
  
  root to: "pergunta#menu"

end

app/controllers/pergunta_controller.rb
class PerguntaController < ApplicationController
  before_action :set_perguntum, only: [:show, :edit, :update, :destroy]


  # GET /menu
  def menu
    
    @list_labels = ['Nivelamento', 'Nível 1', 'Nível 2', 'Nível 3', 'Nível 4', 'Nível 5'];
    @list_pontuacao = [
      'nenhuma pergunta respondida neste nível',
      'nenhuma pergunta respondida neste nível',
      'nenhuma pergunta respondida neste nível',
      'nenhuma pergunta respondida neste nível',
      'nenhuma pergunta respondida neste nível',
      'nenhuma pergunta respondida neste nível'
    ];
    
    @acertos = Respostum.joins("INNER JOIN pergunta ON pergunta.id = resposta.perguntum_id WHERE resposta.resp=pergunta.resp AND resposta.usuario_id = #{current_usuario.id}").count();
    @respondidas = Respostum.joins(:perguntum).where(usuario_id: current_usuario.id, pergunta:{reforco: false}).count()
    @media = (@acertos * 100/@respondidas).round(2).to_s + "%";
    
    @tmp = Respostum.joins("INNER JOIN pergunta ON pergunta.id = resposta.perguntum_id WHERE resposta.resp=pergunta.resp AND resposta.usuario_id = #{current_usuario.id} AND pergunta.nivelamento = 't'").count();
    if (@tmp > 0)
      @list_pontuacao[0] = @tmp.to_s + "/10"
    end
    
    for i in 1..5
      @tmp = Respostum.joins("INNER JOIN pergunta ON pergunta.id = resposta.perguntum_id WHERE resposta.resp=pergunta.resp AND resposta.usuario_id = #{current_usuario.id} AND pergunta.nivel = #{i} AND pergunta.nivelamento = 'f' AND pergunta.reforco = 'f'").count();
      if (@tmp > 0)
        @list_pontuacao[i] = @tmp.to_s + "/10"
      end
    end
    
  end

  # GET /pergunta/
  # GET /pergunta.json
  def index
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
    
    @pergunta = Perguntum.all.order(reforco: :desc).order(:nivel)
  end
  
  # GET /pergunta/1/1
  def listar
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
    
    if params[:reforco] == "1" then
      @perguntum = Perguntum.where(nivel: params[:nivel], reforco: true)
    else
      @perguntum = Perguntum.where(nivel: params[:nivel], reforco: false)
    end
  end
  
  #GET /randomize/nivel/
  def randomize
    @nivel = params[:nivel]
    
    if (@nivel == "0" && current_usuario.premios < 0) then
      @lista = current_usuario.on;
      @lista = @lista.split('-');
      
      for i in 1..10 do
        Respostum.destroy_all(usuario_id: current_usuario.id, perguntum_id: @lista[i-1].to_i);
      end
    end

    if (@nivel == "0") then
      @lista = current_usuario.on;
    elsif (@nivel == "1") then
      @lista = current_usuario.on1;
    elsif (@nivel == "2") then
      @lista = current_usuario.on2;
    elsif (@nivel == "3") then
      @lista = current_usuario.on3;
    elsif (@nivel == "4") then
      @lista = current_usuario.on4;
    elsif (@nivel == "5") then
      @lista = current_usuario.on5;
    elsif (@nivel == "r1") then
      @lista = current_usuario.or1;
    elsif (@nivel == "r2") then
      @lista = current_usuario.or2;
    elsif (@nivel == "r3") then
      @lista = current_usuario.or3;
    elsif (@nivel == "r4") then
      @lista = current_usuario.or4;
    elsif (@nivel == "r5") then
      @lista = current_usuario.or5;      
    end
    
    @lista = @lista.split('-');   
    @lista = @lista.shuffle
    
    @str = @lista[0].to_s;
    for i in 2..10 do
      @str = @str +"-"+ @lista[i-1].to_s;
    end
    
    if (@nivel == "0") then
      current_usuario.on = @str;
    elsif (@nivel == "1") then
      current_usuario.on1 = @str;
    elsif (@nivel == "2") then
      current_usuario.on2 = @str;
    elsif (@nivel == "3") then
      current_usuario.on3 = @str;
    elsif (@nivel == "4") then
      current_usuario.on4 = @str;
    elsif (@nivel == "5") then
      current_usuario.on5 = @str;
    elsif (@nivel == "r1") then
      current_usuario.or1 = @str;
    elsif (@nivel == "r2") then
      current_usuario.or2 = @str;
    elsif (@nivel == "r3") then
      current_usuario.or3 = @str;
    elsif (@nivel == "r4") then
      current_usuario.or4 = @str;
    elsif (@nivel == "r5") then
      current_usuario.or5 = @str;
    end
    
    current_usuario.save;
    
    redirect_to nivel_path(@nivel,1);
  end
  
  # GET /pergunta/1
  # GET /pergunta/1.json
  def show
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
  end

  # GET /pergunta/new
  def new
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
    @perguntum = Perguntum.new
  end

  # GET /pergunta/1/edit
  def edit
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
  end

  # POST /pergunta
  # POST /pergunta.json
  def create
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
    @perguntum = Perguntum.new(perguntum_params)

    respond_to do |format|
      if @perguntum.save
        format.html { redirect_to @perguntum, notice: 'A pergunta foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @perguntum }
      else
        format.html { render :new }
        format.json { render json: @perguntum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pergunta/1
  # PATCH/PUT /pergunta/1.json
  def update
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
    respond_to do |format|
      if @perguntum.update(perguntum_params)
        format.html { redirect_to @perguntum, notice: 'A pergunta foi alterada com sucesso.' }
        format.json { render :show, status: :ok, location: @perguntum }
      else
        format.html { render :edit }
        format.json { render json: @perguntum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pergunta/1
  # DELETE /pergunta/1.json
  def destroy
    if (current_usuario.admin != true)
      redirect_to root_path();
    end
    @perguntum.destroy
    respond_to do |format|
      format.html { redirect_to pergunta_url, notice: 'A pergunta foi excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perguntum
      @perguntum = Perguntum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perguntum_params
      params.require(:perguntum).permit(:pergunta, :conteudo, :op1, :op2, :op3, :justop1, :justop2, :justop3, :resp)
    end
end

app/helpers/pergunta_helper.rb
module PerguntaHelper
    
    def truncate(str)
        @tmp = ""
        if str.length > 100 then
            @tmp = "..."
        end
        
        return str[0..100] + @tmp
    end
    
end

app/views/pergunta/_form.html.erb
<%= form_for(@perguntum) do |f| %>
  <% if @perguntum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perguntum.errors.count, "error") %> prohibited this perguntum from being saved:</h2>

      <ul>
      <% @perguntum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field100">
    <%= f.label :pergunta %><br>
    <%= f.text_area :pergunta %>
  </div>

  <div class="field field100">
    <%= f.label :conteudo %><br>
    <%= f.text_area :conteudo %>
  </div>  
  
  <div class="field field100">
    <%= f.label 'Opção 1' %><br>
    <%= f.text_area :op1 %>
  </div>
  <div class="field field100">
    <%= f.label 'Opção 2' %><br>
    <%= f.text_area :op2 %>
  </div>
  <div class="field field100">
    <%= f.label 'Opção 3' %><br>
    <%= f.text_area :op3 %>
  </div>
  <div class="field field100">
    <%= f.label 'Justificativa de erro da questão 1' %><br>
    <%= f.text_area :justop1 %>
  </div>
  <div class="field field100">
    <%= f.label 'Justificativa de erro da questão 2' %><br>
    <%= f.text_area :justop2 %>
  </div>
  <div class="field field100">
    <%= f.label 'Justificativa de erro da questão 3' %><br>
    <%= f.text_area :justop3 %>
  </div>

  <div class="field field100">
    <%= f.label 'Opção correta' %><br>
    <%= f.select :resp, [['Opção 1', 1], ['Opção 2', 2], ['Opção 3', 3]] %>
  </div>

  <div class="actions btn-group">
    <%= f.submit "Atualizar", class:"btn btn-primary" %>
    <%= link_to 'Voltar', pergunta_path %>
  </div>
<% end %>

app/views/pergunta/edit.html.erb
<h1>Editando pergunta</h1>

<%= render 'form' %>

app/views/pergunta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nivelamento</h1>
  
<table class="table">
    
  <thead>
    <tr>
      <th>Id</th>
      <th>Pergunta</th>
      <th>Opção 1</th>
      <th>Opção 2</th>
      <th>Opção 3</th>
      <th>Justificativa 1</th>
      <th>Justificativa 2</th>
      <th>Justificativa 3</th>
      <th>Resposta</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @pergunta.where(reforco: false, nivelamento: true).each do |perguntum| %>
      <tr>
        <td><%= perguntum.id %></td>
        <td><%= truncate(perguntum.pergunta)%></td>
        <td><%= truncate(perguntum.op1) %></td>
        <td><%= truncate(perguntum.op2) %></td>
        <td><%= truncate(perguntum.op3) %></td>
        <td><%= truncate(perguntum.justop1) %></td>
        <td><%= truncate(perguntum.justop2) %></td>
        <td><%= truncate(perguntum.justop3) %></td>
        <td><%= perguntum.resp %></td>
        <td><%= link_to 'Editar', edit_perguntum_path(perguntum) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>Perguntas</h1>
  
<% for i in 1..5 do %>
  <h3>Nível <%= i %></h3>
  <table class="table">
    
    <thead>
      <tr>
        <th>Id</th>
        <th>Pergunta</th>
        <th>Opção 1</th>
        <th>Opção 2</th>
        <th>Opção 3</th>
        <th>Justificativa 1</th>
        <th>Justificativa 2</th>
        <th>Justificativa 3</th>
        <th>Resposta</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @pergunta.where(nivel: i, reforco: false, nivelamento: false).each do |perguntum| %>
        <tr>
          <td><%= perguntum.id %></td>
          <td><%= truncate(perguntum.pergunta)%></td>
          <td><%= truncate(perguntum.op1) %></td>
          <td><%= truncate(perguntum.op2) %></td>
          <td><%= truncate(perguntum.op3) %></td>
          <td><%= truncate(perguntum.justop1) %></td>
          <td><%= truncate(perguntum.justop2) %></td>
          <td><%= truncate(perguntum.justop3) %></td>
          <td><%= perguntum.resp %></td>
          <td><%= link_to 'Editar', edit_perguntum_path(perguntum) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<h1>Perguntas - Reforço</h1>

<% for i in 1..5 do %>
  <h3>Nível <%= i %></h3>
  <table class="table">
    
    <thead>
      <tr>
        <th>Id</th>
        <th>Pergunta</th>
        <th>Opção 1</th>
        <th>Opção 2</th>
        <th>Opção 3</th>
        <th>Justificativa 1</th>
        <th>Justificativa 2</th>
        <th>Justificativa 3</th>
        <th>Resposta</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @pergunta.where(nivel: i, reforco: true, nivelamento: false).each do |perguntum| %>
        <tr>
          <td><%= perguntum.id %></td>
          <td><%= truncate(perguntum.pergunta)%></td>
          <td><%= truncate(perguntum.op1) %></td>
          <td><%= truncate(perguntum.op2) %></td>
          <td><%= truncate(perguntum.op3) %></td>
          <td><%= truncate(perguntum.justop1) %></td>
          <td><%= truncate(perguntum.justop2) %></td>
          <td><%= truncate(perguntum.justop3) %></td>
          <td><%= perguntum.resp %></td>
          <td><%= link_to 'Editar', edit_perguntum_path(perguntum) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/pergunta/listar.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Pergunta</th>
      <th>Op1</th>
      <th>Op2</th>
      <th>Op3</th>
      <th>Justop1</th>
      <th>Justop2</th>
      <th>Justop3</th>
      <th>Resp</th>
      <th>Nivel</th>
      <th>Reforco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perguntum.each do |perguntum| %>
      <tr>
        <td><%= perguntum.id %></td>
        <td><%= perguntum.pergunta %></td>
        <td><%= perguntum.op1 %></td>
        <td><%= perguntum.op2 %></td>
        <td><%= perguntum.op3 %></td>
        <td><%= perguntum.justop1 %></td>
        <td><%= perguntum.justop2 %></td>
        <td><%= perguntum.justop3 %></td>
        <td><%= perguntum.resp %></td>
        <td><%= perguntum.nivel %></td>
        <td><%= perguntum.reforco %></td>
        <td><%= link_to 'Edit', edit_perguntum_path(perguntum) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pergunta/menu.html.erb
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    
    <% if current_usuario.premios==-1 %>
        <%= link_to 'Nivelamento', randomize_path(0), class: 'btn btn-default'%>
        <%= link_to 'Nível 1', "#", class: 'btn btn-default', disabled: "" %>
        <%= link_to 'Nível 2', "#", class: 'btn btn-default', disabled: "" %>
        <%= link_to 'Nível 3', "#", class: 'btn btn-default', disabled: "" %>
        <%= link_to 'Nível 4', "#", class: 'btn btn-default', disabled: "" %>
        <%= link_to 'Nível 5', "#", class: 'btn btn-default', disabled: "" %>
        
        <%= link_to 'Reforço', "#", class: 'btn btn-default', disabled: ""  %>
    <% end %>   
    
    <% if current_usuario.premios==0 %>
        <%= link_to 'Nivelamento', randomize_path(0), class: 'btn btn-success'%>
        <% if current_usuario.reforco == true then %>
            <%= link_to 'Nível 1', randomize_path(1), class: 'btn btn-danger'%>
        <% else %>
            <%= link_to 'Nível 1', randomize_path(1), class: 'btn btn-default'%>
        <%end %>
        <%= link_to 'Nível 2', "#", class: 'btn btn-default', disabled: ""  %>
        <%= link_to 'Nível 3', "#", class: 'btn btn-default', disabled: ""  %>
        <%= link_to 'Nível 4', "#", class: 'btn btn-default', disabled: ""  %>
        <%= link_to 'Nível 5', "#", class: 'btn btn-default', disabled: ""  %>
        
        <% if current_usuario.reforco == true then %>
            <%= link_to 'Reforço', randomize_path("r1"), class: 'btn btn-default' %>
        <% else %>
            <%= link_to 'Reforço', "#", class: 'btn btn-default', disabled: ""  %>
        <% end %>        
        
    <% end %>
    
    <% if current_usuario.premios==1 %>
        <%= link_to 'Nivelamento', randomize_path(0), class: 'btn btn-default btn-success'%>
        <%= link_to 'Nível 1', randomize_path(1), class: 'btn btn-success' %>
        
        <% if current_usuario.reforco == true then %>
            <%= link_to 'Nível 2', randomize_path(2), class: 'btn btn-danger' %>
        <% else %>
            <%= link_to 'Nível 2', randomize_path(2), class: 'btn btn-default' %>
        <% end %>
        
        <%= link_to 'Nível 3', "#", class: 'btn btn-default', disabled: "" %>
        <%= link_to 'Nível 4', "#", class: 'btn btn-default', disabled: "" %>
        <%= link_to 'Nível 5', "#", class: 'btn btn-default', disabled: "" %>

        <% if current_usuario.reforco == true then %>
            <%= link_to 'Reforço', randomize_path("r2"), class: 'btn btn-default' %>
        <% else %>
            <%= link_to 'Reforço', "#", class: 'btn btn-default', disabled: ""  %>
        <% end %>      
    <% end %>    

    <% if current_usuario.premios==2 %>
        <%= link_to 'Nivelamento', randomize_path(0), class: 'btn btn-success' %>
        <%= link_to 'Nível 1', randomize_path(1), class: 'btn btn-success' %>
        <%= link_to 'Nível 2', randomize_path(2), class: 'btn btn-success'%>
        
        <% if current_usuario.reforco == true then %>
            <%= link_to 'Nível 3', randomize_path(3), class: 'btn btn-danger'%>
        <% else %>
            <%= link_to 'Nível 3', randomize_path(3), class: 'btn btn-default'%>
        <% end %>
        
        <%= link_to 'Nível 4', "#", class: 'btn btn-default', disabled: ""  %>
        <%= link_to 'Nível 5', "#", class: 'btn btn-default', disabled: ""  %>

        <% if current_usuario.reforco == true then %>
            <%= link_to 'Reforço', randomize_path("r3"), class: 'btn btn-default' %>
        <% else %>
            <%= link_to 'Reforço', "#", class: 'btn btn-default', disabled: ""  %>
        <% end %>      
    <% end %>    
    
    <% if current_usuario.premios==3 %>
        <%= link_to 'Nivelamento', randomize_path(0), class: 'btn btn-success' %>
        <%= link_to 'Nível 1', randomize_path(1), class: 'btn btn-success' %>
        <%= link_to 'Nível 2', randomize_path(2), class: 'btn btn-success' %>
        <%= link_to 'Nível 3', randomize_path(3), class: 'btn btn-success' %>
        <% if current_usuario.reforco == true then %>
            <%= link_to 'Nível 4', randomize_path(4), class: 'btn btn-danger' %>
        <% else %>
            <%= link_to 'Nível 4', randomize_path(4), class: 'btn btn-default' %>
        <% end %>
        <%= link_to 'Nível 5', "#", class: 'btn btn-default', disabled: "" %>

        <% if current_usuario.reforco == true then %>
            <%= link_to 'Reforço', randomize_path("r4"), class: 'btn btn-default' %>
        <% else %>
            <%= link_to 'Reforço', "#", class: 'btn btn-default', disabled: ""  %>
        <% end %>      
    <% end %>    
    
    <% if current_usuario.premios==4 %>
        <%= link_to 'Nivelamento', randomize_path(0), class: 'btn btn-success', enabled: true %>
        <%= link_to 'Nível 1', randomize_path(1), class: 'btn btn-success' %>
        <%= link_to 'Nível 2', randomize_path(2), class: 'btn btn-success' %>
        <%= link_to 'Nível 3', randomize_path(3), class: 'btn btn-success' %>
        <%= link_to 'Nível 4', randomize_path(4), class: 'btn btn-success' %>
        
        <% if current_usuario.reforco == true then %>
            <%= link_to 'Nível 5', randomize_path(5), class: 'btn btn-danger' %>
        <% else %>
            <%= link_to 'Nível 5', randomize_path(5), class: 'btn btn-default' %>
        <% end %> 
        
        <% if current_usuario.reforco == true then %>
            <%= link_to 'Reforço', randomize_path("r5"), class: 'btn btn-default' %>
        <% else %>
            <%= link_to 'Reforço', "#", class: 'btn btn-default', disabled: ""  %>
        <% end %>      
    <% end %>    
    
    <% if current_usuario.premios==5 %>
        <%= link_to 'Nivelamento', randomize_path(0), class: 'btn btn-success', enabled: true %>
        <%= link_to 'Nível 1', randomize_path(1), class: 'btn btn-success' %>
        <%= link_to 'Nível 2', randomize_path(2), class: 'btn btn-success' %>
        <%= link_to 'Nível 3', randomize_path(3), class: 'btn btn-success' %>
        <%= link_to 'Nível 4', randomize_path(4), class: 'btn btn-success' %>
        <%= link_to 'Nível 5', randomize_path(5), class: 'btn btn-success' %>
    <% end %>    
                
</div>

    <%
    @premios = current_usuario.premios
    
    if (@premios < 0) then
        @premios = 0; 
    end
    %>
    
    <%= image_tag("img#{@premios}.png", :class=> "consultorio", :alt => "seu consultório com #{@premios} premios") %>
    <center><h3>Você conquistou <%= @premios %> de 5 equipamentos</h3></center>

<% if @premios == 5 %>

    <div class="panel panel-default" style="margin-top:30px;">
      <div class="panel-heading">
        <center><h1 class="panel-title">Parabéns, você concluiu o jogo.</h1></center>
      </div>
      <div class="panel-body">
         
        <center>
            <h4>Você acertou <%=@acertos%> das <%=@respondidas%> pergunta(s) respondidas</h4>
        </center> 
          
        <table class="table">
            <tr>
                <th>Nível</th>
                <th>Pontuação</th>
            </tr>            
            <% for i in 0..5 do %>
            <tr>
                <td><%=@list_labels[i]%></th>
                <td><%=@list_pontuacao[i]%></th>
            </tr>            
            <% end %>
            
            <tr>
                <td colspan="2" align="center" style="background-color:lightblue;"><h4>Média: <%=@media%></h4></th>
            </tr>      
        </table>
      </div>
    </div>

    
<% end %>

app/views/pergunta/new.html.erb
<h1>New Perguntum</h1>

<%= render 'form' %>

<%= link_to 'Back', pergunta_path %>

app/views/pergunta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pergunta:</strong>
  <%= @perguntum.pergunta %>
</p>

<p>
  <strong>Conteúdo:</strong>
  <%= @perguntum.conteudo.html_safe %>
</p>

<p>
  <strong>Op1:</strong>
  <%= @perguntum.op1 %>
</p>

<p>
  <strong>Op2:</strong>
  <%= @perguntum.op2 %>
</p>

<p>
  <strong>Op3:</strong>
  <%= @perguntum.op3 %>
</p>

<p>
  <strong>Justop1:</strong>
  <%= @perguntum.justop1.html_safe %>
</p>

<p>
  <strong>Justop2:</strong>
  <%= @perguntum.justop2.html_safe %>
</p>

<p>
  <strong>Justop3:</strong>
  <%= @perguntum.justop3.html_safe %>
</p>

<p>
  <strong>Resp:</strong>
  <%= @perguntum.resp %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @perguntum.nivel %>
</p>

<p>
  <strong>Reforco:</strong>
  <%= @perguntum.reforco %>
</p>

<%= link_to 'Editar', edit_perguntum_path(@perguntum) %> |
<%= link_to 'Voltar', pergunta_path %>