config/routes.rb
Rails.application.routes.draw do
  resources :resposta
  resources :pergunta
  resources :pergunta
  devise_for :usuarios
  
  get '/menu' => 'pergunta#menu'
  get '/randomize/:nivel' => 'pergunta#randomize', as: 'randomize'
  get '/listar/:nivel/:reforco' => 'pergunta#listar'

  get '/nivel/:nivel/:ordem' => 'resposta#nivel', as: "nivel"
  
  root to: "pergunta#menu"

end

app/controllers/resposta_controller.rb
class RespostaController < ApplicationController
  before_action :set_respostum, only: [:show, :edit, :update, :destroy]
  
  # GET /resposta
  # GET /resposta.json
  def index
    @resposta = Respostum.all
  end

  # GET /resposta/1
  # GET /resposta/1.json
  def show
    redirect_to :back
  end

  # GET /new
  # GET /new.json
  def new
  end
  
  def to_b(str)
    str == 'true'
  end

  # GET /resposta/nivel/1/1/1
  def nivel
    @usuarioId = current_usuario.id;
    @ordem = params[:ordem]
    @nivel = params[:nivel]
    
    @reforco = false;
    @nivelamento = false;
     
    if (@nivel == "0") then
      @nivelamento = true
      @lista = current_usuario.on;
    elsif (@nivel == "1") then
      @lista = current_usuario.on1;
    elsif (@nivel == "2") then
      @lista = current_usuario.on2;
    elsif (@nivel == "3") then
      @lista = current_usuario.on3;
    elsif (@nivel == "4") then
      @lista = current_usuario.on4;
    elsif (@nivel == "5") then
      @lista = current_usuario.on5;
    elsif (@nivel == "r1") then
      @lista = current_usuario.or1;
      @reforco = true;
    elsif (@nivel == "r2") then
      @lista = current_usuario.or2;
      @reforco = true;
    elsif (@nivel == "r3") then
      @lista = current_usuario.or3;
      @reforco = true;
    elsif (@nivel == "r4") then
      @lista = current_usuario.or4;
      @reforco = true;
    elsif (@nivel == "r5") then
      @lista = current_usuario.or5;      
      @reforco = true;
    end
    
        
    
    @lista = @lista.split('-');
    @idPergunta = @lista[@ordem.to_i - 1].to_i;
    
    @perguntum = Perguntum.where(id: @idPergunta).first;
    
    #pega, dependendo do que está no bd, se a resposta foi correta ou não.
    #Respostum.where(perguntum_id: @idPergunta, usuario_id: current_usuario.id)
    
    @cores = ["", "btn-default", "btn-default", "btn-default", "btn-default", "btn-default", "btn-default", "btn-default", "btn-default", "btn-default", "btn-default"];
    @questoesRespondidas = 0
    @questoesCertas = 0
    for i in 1..10 do
  
      @tmp = Respostum.joins(:perguntum).where(usuario_id: current_usuario.id, perguntum_id: @lista[i-1])
      
      if (@tmp.count > 0) then
        @tmp = @tmp.first
        if (@tmp.resp == @tmp.perguntum.resp) then
          @cores[i] = "btn-success"
          @questoesRespondidas = @questoesRespondidas + 1
          @questoesCertas = @questoesCertas + 1
        elsif (@tmp.resp == nil) then
          @cores[i] = "btn-default"
        else
          @cores[i] = "btn-danger"
          @questoesRespondidas = @questoesRespondidas + 1
        end
      end
    end
    
    @aprovado = false;
    @finalizou = false;
    @aprovadoReforco = false;
    @gameover = false;
    
    
    @tmp = Respostum.where(usuario_id: current_usuario.id, perguntum_id: @idPergunta)
    if (@tmp.count==0) then
      @novo = true;
      @respostum = Respostum.new()
      @respostum.usuario_id = current_usuario.id
      @respostum.perguntum_id = @idPergunta
      @respostum.save()
    else
      @respostum = @tmp.first()
      if @respostum.resp == nil then
        @novo = true;
      else
        @novo = false;
      end
    end    
    
    if @questoesRespondidas == 10 then
      @finalizou = true;
      
      @quantidadeAcertos = [0,0,0,0,0];
      @quantidadeQuestoes = [0,0,0,0,0];
      if (@nivelamento == true) then
        
        for i in 0..4
          @quantidadeAcertos[i]  = Respostum.joins("INNER JOIN pergunta ON pergunta.id = resposta.perguntum_id WHERE resposta.resp=pergunta.resp AND resposta.usuario_id = #{current_usuario.id} AND pergunta.nivel = #{i+1}  AND pergunta.nivelamento = 't'").count()
          @quantidadeQuestoes[i] = Respostum.joins("INNER JOIN pergunta ON pergunta.id = resposta.perguntum_id WHERE resposta.usuario_id = #{current_usuario.id} AND pergunta.nivel = #{i+1} AND pergunta.nivelamento = 't'").count()
          # ^ Same ^ @quantidadeQuestoes[i] = Respostum.joins(:perguntum).where(usuario_id: current_usuario.id, pergunta: {nivel:i+1, nivelamento:true}).count()
        end
        
        @premios = 0;
        if (current_usuario.premios = -1) then
          #acertou todas as questões do nivel 1 => apto para o nível 2
          if (@quantidadeAcertos[0] == @quantidadeQuestoes[0]) then
            @premios = 1;
            current_usuario.premios = 1;
            current_usuario.nivelamento = 1;
          
            #acertou todas as questões do nivel 2 => apto para o nível 3
            if (@quantidadeAcertos[1] == @quantidadeQuestoes[1]) then
              @premios = 2;
              current_usuario.premios = 2;
              current_usuario.nivelamento = 2;
            
              #acertou todas as questões do nivel 3 => apto para o nível 4
              if (@quantidadeAcertos[2] == @quantidadeQuestoes[2]) then
                @premios = 3;
                current_usuario.premios = 3;
                current_usuario.nivelamento = 3;
              
                #acertou todas as questões do nivel 4 => apto para o nível 5
                if (@quantidadeAcertos[3] == @quantidadeQuestoes[3]) then
                  @premios = 4;
                  current_usuario.premios = 4;
                  current_usuario.nivelamento = 4;
                end
              end
            end
          else
            @premios = 0;
            current_usuario.premios = 0;
          end
          
          if (current_usuario.premios <= 0)
            current_usuario.reforco = false;
          end
        
          current_usuario.save();
        
        end
      else
        if @questoesCertas >= 7 then
            @aprovado = true;
            if (@nivel!="r1" && @nivel!="r2" && @nivel!="r3" && @nivel!="r4" && @nivel!="r5") then
              current_usuario.erros = 0;
              current_usuario.errossemaforo = true;
            end
        else
            @aprovado = false;
            
            if (current_usuario.errossemaforo==true)&&(@nivel!="r1" && @nivel!="r2" && @nivel!="r3" && @nivel!="r4" && @nivel!="r5") then
              current_usuario.erros = current_usuario.erros + 1;
              current_usuario.errossemaforo = false;
              current_usuario.reforco = true;
              Respostum.joins(:perguntum).destroy_all(usuario_id: current_usuario.id, pergunta: {reforco: true});
              
              if (current_usuario.erros == 3) then
                #reinicializa jogo ignorando o nivelamento
                Respostum.joins(:perguntum).destroy_all(usuario_id: current_usuario.id, pergunta: {nivelamento: false});
                current_usuario.erros = 0;
                current_usuario.errossemaforo = true;
                current_usuario.nivelamento = 0;
                current_usuario.premios = 0;
                current_usuario.reforco = false;
                
                @gameover = true;
              end
            end

            current_usuario.save();
        end
        
        if (@nivel=="r1" || @nivel=="r2" || @nivel=="r3" || @nivel=="r4" || @nivel=="r5") then
          
          if (@nivel == "r1") then
            @listaN = current_usuario.on1;
          elsif (@nivel == "r2") then
            @listaN = current_usuario.on2;
          elsif (@nivel == "r3") then
            @listaN = current_usuario.on3;
          elsif (@nivel == "r4") then
            @listaN = current_usuario.on4;
          elsif (@nivel == "r5") then
            @listaN = current_usuario.on5;      
          end      
          
          @listaN = @listaN.split('-'); 
          
          if @questoesCertas >= 7 then
            #limpa questões do nivel correspondente
            for i in 1..10 do
              Respostum.destroy_all(usuario_id: current_usuario.id, perguntum_id: @listaN[i-1].to_i);
            end
            #aprovadoReforco
            current_usuario.reforco = false;
            current_usuario.errossemaforo = true;
            current_usuario.save();
            @aprovadoReforco=true;
          else
            #limpa questões do nivel atual (do reforço atual)
            for i in 1..10 do
              Respostum.destroy_all(usuario_id: current_usuario.id, perguntum_id: @lista[i-1].to_i);
            end
            @aprovadoReforco=false;
          end
        elsif(@nivel.to_i - 1 == current_usuario.premios)then
          
          if @questoesCertas >= 7 then
            current_usuario.premios = current_usuario.premios + 1;
          else
            #limpa reforco
            if (@nivel == "1" && @nivel == "2" && @nivel == "3" && @nivel == "4" && @nivel == "5") then
              if (@nivel == "1") then
                @listaN = current_usuario.or1;
              elsif (@nivel == "2") then
                @listaN = current_usuario.or2;
              elsif (@nivel == "3") then
                @listaN = current_usuario.or3;
              elsif (@nivel == "4") then
                @listaN = current_usuario.or4;
              elsif (@nivel == "5") then
                @listaN = current_usuario.or5;      
              end
              
              @listaN = @listaN.split('-'); 
              for i in 1..10 do
                Respostum.destroy_all(usuario_id: current_usuario.id, perguntum_id: @listaN[i-1].to_i);
              end
              
              #reforco = true
              current_usuario.reforco = true;
              Respostum.joins(:perguntum).destroy_all(usuario_id: current_usuario.id, pergunta: {reforco: true});
            end
            
          end
  
          current_usuario.save()
        end
      end
      
    end

    

  end

  # GET /resposta/1/edit
  def edit
      
  end

  # POST /resposta
  # POST /resposta.json
  def create
    @respostum = Respostum.new(respostum_params)

    respond_to do |format|
      if @respostum.save
        format.html { redirect_to @respostum, notice: 'Respostum was successfully created.' }
        format.json { render :show, status: :created, location: @respostum }
      else

app/helpers/resposta_helper.rb
module RespostaHelper
end

app/views/resposta/_form.html.erb
<br>

<% if @nivel.to_i <= current_usuario.nivelamento && @nivelamento!=true && @reforco == false then
  @novo = false;
end %>

<%= form_for @respostum do |f| %>
  <% if @respostum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@respostum.errors.count, "error") %> prohibited this respostum from being saved:</h2>

      <ul>
      <% @respostum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @novo==false then %> <% if @perguntum.resp==1 then @alert = "alert-success" else @alert = "alert-danger" end%> <div class="alert <%=@alert%>" role="alert"> <% end %>
    <% if @novo==false then %> <%= radio_button("respostum", "resp", "1", :disabled=>"", :required=>"") %><% end %>
    <% if @novo then %><%= radio_button("respostum", "resp", "1", :required=>"") %><% end %>
    <%= @perguntum.op1 %> <% if @novo then %><br><%end%>
    <% if @novo==false then %> <h4 data-toggle="modal" class="resp-info" data-target="#myModal1"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></h4> <% end %>
  <% if @novo==false then %> </div> <% end %>
  
  <% if @novo==false then %> <% if @perguntum.resp==2 then @alert = "alert-success" else @alert = "alert-danger" end%> <div class="alert <%=@alert%>" role="alert"> <% end %>
    <% if @novo==false then %> <%= radio_button("respostum", "resp", "2", :disabled=>"") %> <% end %>
    <% if @novo then %> <%= radio_button("respostum", "resp", "2") %> <% end %>
    <%= @perguntum.op2 %> <% if @novo then %><br><%end%>
    <% if @novo==false then %> <h4 data-toggle="modal" class="resp-info" data-target="#myModal2"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></h4>  <% end %>
  <% if @novo==false then %> </div> <% end %>

  <% if @novo==false then %> <% if @perguntum.resp==3 then @alert = "alert-success" else @alert = "alert-danger" end%> <div class="alert <%=@alert%>" role="alert"> <% end %> 
    <% if @novo==false then %> <%= radio_button("respostum", "resp", "3", :disabled=>"") %><% end %>
    <% if @novo then %><%= radio_button("respostum", "resp", "3") %><% end %>
    <%= @perguntum.op3 %> <% if @novo then %><br><%end%>
    <% if @novo==false then %> <h4 data-toggle="modal" class="resp-info" data-target="#myModal3"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></h4>  <% end %>
  <% if @novo==false then %> </div> <% end %>
  
  <% if @novo then %>
    <div class="actions" style="margin-top:25px;">
      <%=  f.submit :Corrigir, class: 'btn btn-primary' %>
    </div>
  <% elsif (@respostum.resp.to_s != "") then
    if @respostum.resp == @perguntum.resp then %>
      <h3 style="color:green"><span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span> Parabéns, você acertou</h3>
    <% else %>
      <h3 style="color:red"><span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span> Você errou</h3>
      <% if @respostum.resp == 1 then @just = @perguntum.justop1.html_safe end %>
      <% if @respostum.resp == 2 then @just = @perguntum.justop2.html_safe end %>
      <% if @respostum.resp == 3 then @just = @perguntum.justop3.html_safe end %>
      <h4><%= @just %></h4>
    <% end %> 
  <% end %>
<% end %>


  <!-- Modal Justificativa 1 -->
  <div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Justificativa da resposta 1</h4>
        </div>
        <div class="modal-body">
          <p><%= @perguntum.justop1.html_safe %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Modal Justificativa 2 -->
  <div class="modal fade" id="myModal2" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Justificativa da resposta 2</h4>
        </div>
        <div class="modal-body">
          <p><%= @perguntum.justop2.html_safe %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>  
  
  <!-- Modal Justificativa 3 -->
  <div class="modal fade" id="myModal3" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Justificativa da resposta 3</h4>
        </div>
        <div class="modal-body">
          <p><%= @perguntum.justop3.html_safe %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>   

app/views/resposta/edit.html.erb
<h1>Editing Respostum</h1>

<%= render 'form' %>

<%= link_to 'Show', @respostum %> |
<%= link_to 'Back', resposta_path %>

app/views/resposta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resposta</h1>

<table>
  <% @resposta.each do |respostum| %>
  
  <thead>
    <tr>
      <th>Pergunta</th>
    </tr>
  </thead>

  <tbody>
    
      <tr>
        <td><%= form_for(respostum) do |f| %>
  <% if respostum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(respostum.errors.count, "error") %> prohibited this respostum from being saved:</h2>

      <ul>
      <% @respostum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.text_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :perguntum_id %><br>
    <%= f.text_field :perguntum_id %>
  </div>
  <div class="field">
    <%= f.label :resp %><br>
    <%= f.text_field :resp %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</td>

      </tr>
    
  </tbody>
  
  <% end %>
</table>

<br>

<%= link_to 'New Respostum', new_respostum_path %>

app/views/resposta/new.html.erb
<h1>aa</h1>

<% @perguntum.each do |p| %>
  <%= p %><br/>
<% end %>

<% @perguntum.where(nivel: 1, reforco: false, nivelamento: false).each do |perguntum| %>
    <%= perguntum.pergunta %>
    <%= perguntum.op1 %>
    <%= perguntum.op2 %>
    <%= perguntum.op3 %>
    <%= perguntum.justop1 %>
    <%= perguntum.justop2 %>
    <%= perguntum.justop3 %>
    <%= perguntum.resp %>
    <%= perguntum.nivel %>
    <%= perguntum.reforco %>
    <%= perguntum.nivelamento %>
      
    <%= render 'form' %>
<% end %>


<%= link_to 'Back', resposta_path %>

app/views/resposta/nivel.html.erb
<div class="page-header">
    <h1>
        <% if @nivelamento==true then %>
            Nivelamento
        <% elsif @reforco==true then %>
            Reforço do nível: <%= @nivel[1] %>
        <% else %>
            Nível: <%= @nivel %>
        <% end %>
        <small>Pergunta <%= @ordem %> de 10</small>
    </h1>
</div>

<div class="btn-group" role="group">
    <% for i in 1..10 do %>
        <%
            @tmp = "";
            if i==@ordem.to_i then
                @tmp = "<span class='glyphicon glyphicon-arrow-up' aria-hidden='true' style='margin-top:10px;'></span>";
            end
        %>     
        
        <%= link_to(nivel_path(@nivel,i), class: "btn btn-default #{@cores[i]}", style: "#{@tmp}; height:34px") do %>
          <%= i.to_s%>
          <br>
          <%= @tmp.html_safe %>
        <% end %>
        
    <% end %>
</div>

<%if (@nivelamento==false && @reforco==false && @nivel.to_i <= current_usuario.nivelamento) then%>
    <div class="panel panel-default">
        <div class="panel-body">
            <h4>Você pulou este nível por conta do nivelamento</h4>
            Mas ainda pode conferir o gabarito
        </div>
    </div>
<%elsif @finalizou == true then%>
    <div class="panel panel-default">
        <div class="panel-body">
            <%if (@nivelamento == true) then%>
                <h4>Você concluiu o nivelamento.</h4>
                
                <table class="table">
                <% for i in 0..4 %>
                    <tr><td>Você acertou <%=@quantidadeAcertos[i]%> das <%=@quantidadeQuestoes[i]%> questões do nível <%= i+1 %><br></td></tr>
                <% end %>
                </table>
                
                Você está apto para o nível <%=@premios.to_i+1%>.
                
                <% if @premios > 0 then %>
                    Seus prêmios:
                <%end%>
                <% if @premios >= 1 then %>
                    <div class="well well-sm">Materiais de escritório</div> 
                <%end%>
                <% if @premios >= 2 then %>
                    <div class="well well-sm">Escada</div> 
                <%end%>
                <% if @premios >= 3 then %>
                    <div class="well well-sm">Negatoscópio</div> 
                <%end%>
                <% if @premios >= 4 then %>
                    <div class="well well-sm">Quadro</div> 
                <%end%>
                
                <%= link_to 'Menu', menu_path, class: 'btn btn-default'%>
            <%elsif (@aprovadoReforco == true) then%>
                <h1 style="color:green; float:left; margin-right:20px;"><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span></h1>
                <h4>Parabéns, você concluiu o reforço.</h4>
                Um nível foi liberado: <%= link_to 'Menu', menu_path, class: 'btn btn-default'%>
            <%elsif (@aprovado == true) then%>
                <h1 style="color:green; float:left; margin-right:20px;"><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span></h1>
                <h4>Parabéns. Você acertou mais de 70% das perguntas e foi aprovado</h4>
                Você ganhou um prêmio
                
                <%if (@nivelamento!="true") then%>
                    <%if (@nivel=="1") then%>
                        : <b>Materiais de escritório</b>.
                    <%elsif (@nivel=="2") then%>
                        : <b>Escada</b>.
                    <%elsif (@nivel=="3") then%>
                        : <b>Negatoscópio</b>.
                    <%elsif (@nivel=="4") then%>
                        : <b>Quadro</b>.
                    <%elsif (@nivel=="5") then%>
                        : <b>Maca</b>.
                    <%end%>
                <%end%>
            <%else%>
                <h1 style="color:red; float:left; margin-right:20px;"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></h1>
                <h4>Infelizmente você não foi aprovado. </h4>
                
                <%if (@gameover == true) then%>
                    GAMEOVER: Você foi reprovado no mesmo nível mais de duas vezes, então o jogo irá reiniciar.
                <%else %>
                    Verifique o menu para fazer 
                    <%if @reforco!=true then%>
                        novamente 
                    <%end%>
                    o reforço: <%= link_to 'Menu', menu_path, class: 'btn btn-default'%>
                    <br>
                    <% if (@nivelamento == false && @reforco == false) then %>
                        Você tem mais <%=3 - current_usuario.erros%> chances para ser aprovado neste nível.
                    <% end %>
                <%end%>
            <%end%>
        </div>
    </div>
    
<% end %>

<div class="jumbotron">

    <h4><%= @perguntum.pergunta %></h4>
    
    <%= @perguntum.conteudo.html_safe %> <br>
    
    <%= render 'form' %>

</div>

<!-- avisar que vai perder a resposta -->
<% if @ordem.to_i > 1 then %>
    <%= link_to 'Anterior', nivel_path(@nivel, @ordem.to_i - 1), class: 'btn btn-default' %>  <!-- voltar para o anterior (@ordem - 1) -->
<% end %>

<% if @ordem.to_i < 10 then %>
    <%= link_to 'Próxima', nivel_path(@nivel, @ordem.to_i + 1), class: 'btn btn-default', style:'float:right' %> <!-- vai para a próxima (@ordem + 1) -->
<% end %>
<!-- fim do aviso -->

app/views/resposta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @respostum.usuario.id %>
  <br>
  <%= @respostum.usuario.nome %>
</p>

<p>
  <strong>Perguntum:</strong>
  <%= @respostum.perguntum %>
</p>

<p>
  <strong>Resp:</strong>
  <%= @respostum.resp %>
</p>

<%= link_to 'Edit', edit_respostum_path(@respostum) %> |
<%= link_to 'Back', resposta_path %>