config/routes.rb
Rails.application.routes.draw do
  resources :resposta
  resources :pergunta
  resources :pergunta
  devise_for :usuarios
  
  get '/menu' => 'pergunta#menu'
  get '/randomize/:nivel' => 'pergunta#randomize', as: 'randomize'
  get '/listar/:nivel/:reforco' => 'pergunta#listar'

  get '/nivel/:nivel/:ordem' => 'resposta#nivel', as: "nivel"
  
  root to: "pergunta#menu"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MEDEDUC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container ">
        <div id="logo" class="navbar-brand"><%= link_to "MEDEDUC", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
            <% if usuario_signed_in? %>
              <li><%= link_to 'Editar seu cadastro', edit_usuario_registration_path %></li>
              <% if current_usuario.admin == true %>
                <li><%= link_to 'Editar perguntas', pergunta_path %></li>
              <% end %>
              <li><%= link_to 'Sair', destroy_usuario_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to 'Entre', new_usuario_session_path %></li>
              <li><%= link_to 'Cadastre-se', new_usuario_registration_path %></li>
            <% end %>
        </ul>
        </nav>
      </div>
    </div>
  </header>

  <div id="main_content" class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

      <div id="content" class="col-md-12 center-block">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>